### ISSUE TITLE
To extend our set of rules with an existing one (example airbnb-base)

### ISSUE THREAD

**Issue by dominguezcelada** [Marfeel/MarfeelCodingStandards#3]
What about extending our rules-set with an existing one and override the rules we are not agree with?

Example: https://github.com/airbnb/javascript

**Comment by alexmrf** [comment]
TLDR Because we have our own coding standards. 

IMHO, extending makes sense if you are bootstraping a new project and you will decide to base the project standards in an existing rule-set. When we defined Marfeel's eslint, was based on Marfeel best practices, with @marcmrf we reviewed one-by-one all the rules. Doing the diff with another rule-set makes no sense for me.

**Comment by marcmrf** [comment]
can you be more specific about which rules do you want to add, modify, or why do you want a new one?

**Comment by dominguezcelada** [comment]
- To me (and I think for more of us) it's a way to learn different ways to write the same in JS.
- To _standarize_ the code in scenarios we don't have a convention yet.

If we don't want to do an extension since it's a started project and it's painful to migrate it, I suggest to extend an existing ESLint (airbnb for example), overwrite to put all the rules to off and progressively enable the ones discussed as issues here in the repo. What do you think?

**Comment by dominguezcelada** [comment]
Closing the issue due to inactivity. I will pop up the ESLint rules I find interesting from other rule sets.
